### PR TITLE
Custom Multi Chain Cosmwasm Client, CLI Wallet command enhancement, CLI Multi Env, and bug fixes

### PR DESCRIPTION
**Pull request by SlayerAnsh**
Note - Ignore adocodegen diffs as these are autogerated

# ANDRJS

### Cosmwasm Client
As there are multiple chains AOS is interacting with, it was hard to manage clients using their own packages specially because it all comes to signer and pubkey. Major refactor is done to `CosmWasm` Client using by `AndromedaClient` to support multiple pubkey. With this update, custom packages for terra and archway clients were removed.

### Wallet Client
Wallet Client is also updated to now use mnemonic or private key and encrypt it using its own encryption method. This will help clients to use same wallet for multiple chains which was not possible with previous Client. (This feature has more impact on CLI wallet feature which we will discuss below)

### Schema Client and GQL Client
Schema client was internally using env variable for fallback which was not visible cleary to library users. Now Andromeda Client needs schema url as constructor.
Gql client is not part of AndromedaClient but it was also using env variable, you can update gql client now using `setGQLSdkUri`.

### Bug Fixes
With latest updates to chains, there were some bugs with msg parsing related to store code mainly. Now with new Cosmwasm client implementation, all messages are wrapped inside there own encoder and we have implemented event parsing logic with all the fallbacks that are needed to support events from multiple chains

# CLI

### Wallet Command
Wallet command is refactored completely and now supports both mnemonic and private key. In contrast to previous version were you need to store your wallet for each chain, now same wallet can be used for multiple chain. Encryption method for wallet store has been updated (Any suggestion regarding other, more secure encyption method are highly welcomed).

- wallets recover - Add a wallet with private key(new feature) or mnemonic
- wallets generate - Generate a new wallet with mnemonic
- wallets rename - Rename your wallet (New Feature)
- wallets migrate-legacy - As encryption has been updated, users can use this method to migrate there legacy wallets to new configuration. You cannot use old wallet without migrating
- wallets reveal - reveal encypted/stored mnemonic or private key (New Feature)
- wallets autosave - Enable/Disable keychain store for a wallet (New Feature) (Advance Usage)

### ENV Command
One of the issues that I personally face with any wallet provider is isolation of different env. I want to use 5-6 testing wallets but don't want to accidently use these for any mainnet stuff. With new env you can isolate your keys and configs inside an env and quickly shift between them.

- env use - Change env. You can also use this to import new env if your env is not listed
- env update - Update env fields - gql url, schema url and name
- env print - show current env config

### Chain Command
Updated localchains storage to fix all the local config related bugs. Localchains are also part of env so you can set different chains per env.
- chain use - Now lists all locally stored chains as well
- chain set - Can only set locally stored chain. Field name is now a select input
- chain list - This command only returns locally created chains. Flag would be added in next iterations to show all chains
- chain new - Added kernel address and coinType field, removed registry address field

## Summary by CodeRabbit

- **New Features**
	- Introduced a configuration file to manage review processes, allowing for more granular control over which parts of the codebase are subject to review.
	- Added a new configuration structure for changeset management, facilitating version tracking across components.

- **Chores**
	- Updated script commands and dependency versions in `package.json` for improved clarity and compatibility.

### CODE REVIEW

**Comment by SlayerAnsh** [comment]
@coderabbitai resolve

**Comment by SlayerAnsh** [comment]
@coderabbitai review

**Comment by SlayerAnsh** [comment]
Please ignore change requests for adocodegen packages, they are autogenerated.

**Review by leifasorensen — APPROVED** [review]
This merge is primarily focused on the updated releases for GraphQL and AndromedaJS and their updates and bug resolutions. These two will be pushed out through the dependency based apps. (CLI release is slated for later, and overlap is discussed in FW section below).

Future Work:
Some additional changes are slated for the CLI (and should be completed in the near future).

**Pull request merged**
